# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull-request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn clean install
      run: mvn -B package --file pom.xml

   - name: Build and push Docker image # construye la imagen y la sube a docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: bitminds/bitminds-rakoon
        tags: latest
        registry: docker.io
        dockerfile: local.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }} # secrets que definimos en la configuracion del repositorio
        password: ${{ secrets.DOCKER_PASSWORD }}
